#!/bin/bash

# 0. you might need to chmod -R 777 ~/.config/counterpartyd before running this
# 1. if testnet/testcoin you might want to config rpc-port to 4000

docker run -i -t -p 172.17.42.1:4000:4000 -v ~/.config/counterpartyd:/.config/counterpartyd:rw counterpartyd --rpc-host 0.0.0.0 server $1 $2 $3 $4 $5 $6 $7 $8 $9

