#!/bin/bash

# 0. you might need to chmod -R 777 ~/.config/counterpartyd before running this
# 1. bitcoin-rpc port has to be on the interface that host container can share, such as 172.17.42.1(docker ip) or local network ip, not 127.0.0.1
# 2. if testnet/testcoin you might want to config rpc-port to 4000

docker run -i -t -p 172.17.42.1:4000:4000 -v ~/.config/counterpartyd:/.config/counterpartyd:rw counterpartyd server $1 $2 $3 $4 $5 $6 $7 $8 $9

